pluralsh/documentation

- README.md
- SUMMARY.md
- api/introduction/console-api.md
- architecture-1.md
- Added quickstart to home page
- Fixed typos, spelling
> Docs cleanup

- getting-started/README.md
- getting-started/cloud-shell-quickstart.md
- operator-guides/README.md
- Fixing title in SUMMARY.md for operator guides
- Adding readme for operator guides
> Update quickstart README and Operator Guides title in SUMMARY

- SUMMARY.md
- Fixing sidebar by updating SUMMARY.md
> Update SUMMARY.md for real.

- adding-new-application/README.md
Adding more details on the testing locally section of adding new application
> Testing locally

- getting-started/README.md
- repositories/README.md
- Edits step 4 of CLI quickstar to refer to the new OAuth workflow.
> Update CLI Quickstart with OAuth instructions

- basics/GettingStarted.md
- getting-started/README.md
- getting-started/cloud-shell.md
- identity-and-access-management/identity-and-installations/sharing-existing-plural-installation-repos.md
For clarity and correct wording
> Rename github to GitHub

- README.md
- SUMMARY.md
- basic-setup-and-deployment/openid-connect.md
- basic-setup-and-deployment/quickstart.md
- quickstart.md
- Our directory structure got a little wonky from the previous changes, fixing this.
> Fix directory pathing

- README.md
- Makes it a little more clear what our two deployment options are.
> Clarify the deployment options in Get Started

- SUMMARY.md
- advanced-topics/network-configuration.md
- Adds the networking guide written by @michaeljguarino with some updates for devX.
> Add networking config guide.

- src/components/PageGrid.tsx
https://linear.app/pluralsh/issue/ENG-656#comment-b36f0a17
> Fix page grid issue

- src/components/GithubStars.tsx
- src/components/MobileMenu.tsx
- src/components/md/Image.tsx
- yarn.lock
- Make github stars badge into two separate links - Add extra vertical padding to images and videos
> Small visual adjustments

- reference/troubleshooting.md
We had a user in discord hit this, and it's a pretty repeatable issue we can document
> Add load balancer controller help doc

- pages/getting-started/quickstart.md
- Updates our Docker image in the Quickstart to be pinned to a stable current release.
> Update Docker image in Quickstart

- package.json
- pages/_app.tsx
- pages/_document.tsx
- pages/reference/configuring-cloud-provider.md
- pages/test/codefence.md
- pages/test/codetabs.md
- pages/test/index.md
- pages/test/tabs.md
- src/components/PageHeader.tsx
- src/components/PageHeaderButtons.tsx
- src/components/SideNav.tsx
- src/components/TableOfContents.tsx
- src/components/md/Button.tsx
- src/components/md/Code.tsx
- src/components/md/CodeTabs.tsx
- src/components/md/Fence.tsx
- src/components/md/Tabs.tsx
- src/markdoc/config/index.ts
- src/markdoc/nodes/fence.markdoc.ts
- src/markdoc/nodes/paragraph.markdoc.ts
- src/markdoc/nodes/table.markdoc.ts
- src/markdoc/tags/button.markdoc.ts
- src/markdoc/tags/callout.markdoc.ts
- src/markdoc/tags/codetabs.markdoc.ts
- src/markdoc/tags/figure.markdoc.ts
- src/markdoc/tags/index.ts
- src/markdoc/tags/tabs.markdoc.ts
- yarn.lock
- Better SEO on regular tabs
- Add `codetabs` tag for rendering `Code` component with tabs
> Tabs improvements

- Makefile
- pages/basic-setup-and-deployment/admin-console.md
Intuned hit this, and I still need to answer questions on it
> Add more explanation for updating git auth

- src/NavData.tsx
- Removing Workspaces from the side nav
> Remove workspaces in Reference Nav

- README.md
info for people that want to contribute for our docs
> Add contribution details

- pages/applications/index.md
Changes repo docs title to app catalog
> Change title name for app catalog

- pages/operations/uninstall.md
Add documentation for:
- plural shell purge
- terraform destroy
- plural repos reset
> Extend current destruction docs

- pages/applications/airflow.mdpart
- src/NavData.tsx
It looks cleaner to not have the icons in the sidebar... unfortunately :(
> Remove icons from docs sidebar

- pages/debugging/application-issues.md
- src/NavData.tsx
Adds doc to debugging on basic k8s operations for debugging applications
> Add section in debugging on deleting K8s pods

- pages/index.md
- Adds note about not supporting BYOK
- Changes language in the intro to be more direct about what we actually do
> Update docs introduction to be more descriptive

- src/NavData.tsx
- fix link in Navdata to fix 404
> Fix doc reference in NavData to the application debugging page

- pages/debugging/application-issues.md
- pages/getting-started/quickstart.md
noticed a few things that have now been fixed or could be improved from recent docs changes
> Small documentation tweaks

- pages/reference/configuring-cloud-provider.md
Telling users how to regenerate their kubeconfig on AWS
> Add info on aws kubeconfig regeneration

- pages/operations/cost-management.md
- src/NavData.tsx
Adds a section that goes over using the Plural Console to perform cost management operations.
> Add Cost Management page to Operations section

- pages/getting-started/manage-git-repositories/workspace-encryption.md
- src/NavData.tsx
- Adds guide on how to use `plural crypto backups`
> Add workspace encryption guide

- pages/operations/cluster-configuration.md
- pages/operations/cost-management.md
- src/NavData.tsx
- Adds doc on how to modify terraform to change Plural defaults
> Add doc on cluster configuration

- pages/reference/configuring-cloud-provider.md
Adding note about azure subscription type mattering for availability
> Add caveat for azure deployments

- pages/operations/cost-management.md
For whatever reason the relative link wasn't working, this should fix it
> Fix node sizing link

- pages/getting-started/cloud-shell-quickstart.md
- Adds the Azure video to the Cloud Shell Quickstart
> Add Azure video to documentation

- cli-readme/README.md
- pages/getting-started/quickstart.md
Will be bootstrapped as the readme for installation repos
n/a
> Add workspace readme

- pages/getting-started/quickstart.md
Some bash magic to get latest vsn and then use it for the download url
> Add general curl installer

- pages/applications/prefect.mdpart
- Adds application specific guide for Prefect
> Add Prefect application guide

- pages/applications/postgres.mdpart
- Removed NodeAffinity from Postgres example YAML
- fixed inline code formatting
- fixed decode command argument
> Fix some small issues with postgres doc

- pages/applications/dagster.mdpart
adds specific dagster deployment guide
> add dagster deployment guide

- package.json
- pages/operations/pricing-calculator.md
- src/NavData.tsx
- src/markdoc/tags/calculator.markdoc.ts
- src/markdoc/tags/index.ts
- yarn.lock
Added pricing calculator markdoc tag and new docs page.
Notes:
- I have added Pricing Calculator page directly in Operations category. In Figma Pricing calculator is under Cost Management. Let me know if you would like to change its placement.
- Page content needs to be reviewed and updated. I have added only few quick mocks.
- Do we want to start using expandable callouts in docs or keep them always expanded like now? If we would like to use expandable variant then this functionality needs to be added.
Feel free to edit it.
Tested locally.
> feat: Pricing calculator

- pages/adding-new-application/guide.md
- Fixed broken links
- Fix directory typo in the guide for adding an application
> fix: doc "Add an application"

- pages/getting-started/quickstart.md
We aren't updating this frequently enough that it is more damage than good i think
n/a
> Remove AMI instructions

- pages/getting-started/concepts.md
- src/NavData.tsx
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204301450124872
> add initial concepts page

- pages/getting-started/cloud-shell-quickstart.md
- pages/getting-started/video-cli-quickstart.md
> Use new cloud shell video in quickstart

- pages/getting-started/manage-git-repositories/sharing-git-repositories.md
Fix broken link in docs for sharing Git repositories
> Fix link to profile public keys

- pages/reference/partial-installation.md
- src/NavData.tsx
Have noticed some users hit these still, and can be complex to unjam.  Some docs could help and will also populate in plural ai.
n/a
> feat: Partial Deployment Docs

- package.json
- src/components/DocSearchStyles.tsx
- src/generated/graphql.ts
- yarn.lock
Units were missing in a css variable, so there was no spacing/padding within search box.
> fix: Missing padding in search box

- pages/deployments/cluster-cost.md
- pages/deployments/helm.md
- pages/deployments/operator/architecture.md
- pages/deployments/operator/git-service.md
- pages/deployments/operator/global-service.md
- pages/deployments/operator/helm-service.md
- pages/deployments/operator/pipeline.md
- pages/deployments/using-operator.md
- src/NavData.tsx
- src/generated/pages.json
This is going to be a very common workflow and probably needs to be better documented, but this will do for now.
local
> Add docs for using the Plural Operator

- pages/deployments/cli-quickstart.md
- pages/deployments/cluster-cost.md
- pages/deployments/cluster-create.md
- pages/deployments/credentials.md
- pages/deployments/import-cluster.md
- pages/deployments/services-deploy.md
- src/NavData.tsx
Also backfills some missing terraform docs.  I think we probably need to devote an entire section to the terraform provider but not handling that for now.  We'd also ideally embed a getting started video in here.
> Document plural up

- pages/deployments/templating.md
> feat: show how to exclude secrets from tf overwriting them

- pages/deployments/sandboxing.md
this is a better solve for those unwilling to vendor repos.
n/a
> Add docs for airgapped deprecations+compatibilities

- pages/deployments/existing-cluster.md
- pages/deployments/private-ca.md
- src/NavData.tsx
This is needed for some private network setups
pr link
> Document how to configure Private CAs

- pages/deployments/cli-quickstart.md
- pages/deployments/existing-cluster.md
- src/NavData.tsx
Add cli install instructions to fleet management quickstart page, also add more command documentation in byok setup page.
n/a
> Minor docs improvements

- pages/deployments/pr/pipelines.md
Explain how to crd configure integration tests in a pipeline
n/a
> Add docs for pipeline integration tests

- .github/workflows/cron.yaml
- Makefile
- pages/deployments/operator/api.md
- src/NavData.tsx
Automates this every week so they don't become stale.
n/a
> Generate operator api docs

- pages/adding-new-application/getting-started-with-runbooks/runbook-yaml.md
- pages/adding-new-application/plural-custom-resources.md
Context: https://discord.com/channels/880830238723047424/1229549563678031893
> Update memory queries to ensure only containers are measured

- .github/workflows/cron.yaml
- pages/deployments/operator/api.md
> Gen new crd docs

- pages/deployments/sandboxing.md
Needed to configure custom console domains.
n/a
> Add oidc redirect url docs

- pages/deployments/dashboard.md
- src/NavData.tsx
We need to document how to set up rbac for the integrated k8s dashboard.
n/a
> Add kubernetes dashboard docs

- .github/workflows/cron.yaml
Permissions weren't properly bound to the gh action
in gh action
> Fix docs updater cron

- pages/deployments/multi-tenancy.md
- src/NavData.tsx
- src/generated/pages.json
> Document Projects and multi-tenancy

- Makefile
The url changed w/ the go client refactor
n/a
> Fix crd docgen

- .github/PULL_REQUEST_TEMPLATE.md
- pages/deployments/dashboard.md
- pages/deployments/notifications.md
- pages/deployments/operator/architecture.md
- pages/deployments/operator/helm-service.md
- pages/deployments/terraform-interop.md
- src/NavData.tsx
* moved service contexts to the stacks docs
* fixup on notifications docs
* fixup on CD docs
Fixes PROD-2666
n/a
> Rearrange some docs, rewrite some other docs

- pages/ai/architecture.md
- pages/ai/cost.md
- pages/ai/overview.md
- pages/ai/setup.md
- pages/catalog/contributing.md
- pages/catalog/creation.md
- pages/catalog/overview.md
- pages/faq/certifications.md
- pages/introduction.md
- src/NavData.tsx
- src/generated/graphql.ts
- src/generated/pages.json
Documents new functionality under our service catalog + AI.
Pending videos for each section...
> Document Service Catalogs + AI

- pages/ai/overview.md
- pages/catalog/overview.md
Videos didn't have audio streams originally
> Fix Youtube links

- pages/how-to/set-up/scm-connection.md
> fix scm name for onboarding

- src/components/PageHeader.tsx
This is a dead link on main plural website
> Remove marketplace link

- pages/deployments/existing-cluster.md
- src/NavData.tsx
Push a lot of common docs changes
> Docs cleanup omnibus

- next.config.js
- src/routes/docs.generated.ts
- src/routing/navigation.ts
- tsconfig.json
quick patch to set up redirects for all the files moved in #402 
also small tsconfig fix
> add new redirects

- pages/index.tsx
> fix: correcting new landing page links

- .github/workflows/ci.yaml
- .github/workflows/cron.yaml
- Makefile
- pages/overview/agent-api-reference.md
- pages/overview/management-api-reference.md
> fix: Docs sync

- pages/plural-features/flows/index.md
> Add demo video for flows

- pages/resources/product-updates.md
> docs: new product update

- generated/routes.json
- pages/plural-features/flows/index.md
- pages/plural-features/flows/preview-environments.md
- pages/plural-features/k8s-upgrade-assistant/index.md
- src/generated/graphql.ts
- src/routing/docs-structure.ts
Documents basic lifecycle of preview environments, and also links out to a quick demo.  Backfilled demo videos for upgrade assistant and flows.
> Preview Environments Documentation

- generated/routes.json
- pages/plural-features/k8s-upgrade-assistant/cluster-drain.md
- src/routing/docs-structure.ts
This is a useful workflow we released a while ago but never truly documented
> Document ClusterDrain controller

- pages/plural-features/projects-and-multi-tenancy/index.md
This is not immediately clear from the yaml, add some comments to tie it together
> Add more clarification on the multi-tenancy docs

- pages/plural-features/pr-automation/crds.md
> Change configRef name

- generated/routes.json
- pages/plural-features/continuous-deployment/helm-service.md
- pages/plural-features/continuous-deployment/lua.md
- src/generated/graphql.ts
- src/routing/docs-structure.ts
> add lua script doc
