pluralsh/documentation

- advanced-topics/identity-and-access-management/identity-and-installations/sharing-existing-repos.md
Santiago hit a weird snag with a service account migration and our oidc proxy we should document.  Also the details of how encryption actually works was a bit unclear, so linking to that reference is probably helpful as well.
> Allbirds docs feedback

- src/components/SideNav.tsx
- src/utils/scrollIntoContainerView.ts
- Allow scrolling in left margin of SideNav
- Replace wonky behavior of scrollIntoView() with custom version:
- Allows explicitly specifying scroll container to avoid unpredictable scrolling of ancestors
- Adds offsetBlock and offsetInline options for giving some padding around the scroll
> Fix scrolling issues

- advanced-topics/identity-and-access-management/identity-and-installations/sharing-existing-repos.md
I've seen a number of users trip on this issue, a simple hint should probably clarify it.
> Add hint about adding install permissions to service accounts

- next.config.js
We link to this often and it's now broken, so adding a redirect.
> Add redirection for /getting-started

- pages/reference/troubleshooting.md
Just tells people to run `plural wkspace kube-init`.  I think this is fairly common in cloudshell initialization, might want to fix that too.
> Add kubeconfig missing docs

- pages/_document.tsx
- src/components/ExternalScripts.tsx
- src/components/types/window.d.ts
- src/gql/graphql.ts
gtag events weren't actually firing, and it turns out cookiebot had automatic support for managing gtag's consent mode, so just using the bare minimum gtag snippet works better.
Not necessary, but updated the TS interface for Cookiebot to be more complete for good measure.
Also a bunch of autogenerated graphql stuff changed.
> fix: Google analytics wasn't working

- pages/reference/configuring-cloud-provider.md
- Refines the plural gcp `reference/configuring-cloud-provider#installation` documentation, addressing permission-related issues that arose for me from discrepancies between the gcloud CLI configuration and the Application Default Credentials (ADC).
- the plural CLI uses both gcloud CLI commands and the gcloud SDK, so both need to be aligned if a user has multiple gcloud configurations 
- Added instructions to ensure users align their gcloud CLI and ADC setup with the same Google Cloud account, to prevent any permission conflicts.
> fix(docs): Update Documentation for gcloud CLI and ADC Setup

- pages/sitemap.xml.ts
- src/components/MainContent.tsx
- src/generated/graphql.ts
- src/generated/pages.json
Adds a new `<article class="primary-content">` wrapper for scrapers to target the main content of each page.
> feat: Add hooks for content scraper

- pages/getting-started/manage-git-repositories/sharing-git-repositories.md
the sharing doc doesn't actually give decryption instructions, this should fix
n/a
> fix sharing git repo docs

- pages/getting-started/manage-git-repositories/sharing-git-repositories.md
There's a confusing interaction w/ users that haven't run `plural login` but are trying to register keys. This should explain.
n/a
> Add login to setup-keys docs

- pages/deployments/advanced-configuration.md
- pages/deployments/ci-gh-actions.md
- pages/deployments/monitoring-addons.md
- pages/deployments/network-configuration.md
- src/NavData.tsx
- src/generated/pages.json
Documenting some more advanced workflows around setting up monitoring, ingress, self-hosted github actions runners.
n/a
> Document setting up grafana agent, github runners, split ingress

- pages/stacks/auto-cancellation.md
- pages/stacks/custom-stacks.md
- src/NavData.tsx
Document the new custom stacks and monitor-based auto-cancellation features we've exposed.  This seems straightfoward enough for now.
n/a
> Document Custom Stacks + Observability autocancellation

- pages/deployments/pr/testing.md
- src/NavData.tsx
Adding docs for pr automation testing strategies.
n/a
> Document PR Automation Testing

- .github/workflows/cron.yaml
- Makefile
- pages/deployments/templating-filters.md
- pages/deployments/templating.md
- pages/index.tsx
- src/NavData.tsx
- src/generated/graphql.ts
- src/generated/pages.json
> feat: Document Liquid template functions

- .vscode/settings.json
- next.config.js
- package.json
- pages/[...slug].tsx
- pages/how-to/set-up/mgmt-cluster.md
- src/generated/graphql.ts
- src/markdoc/mdParser.ts
- src/markdoc/mdSchema.ts
- src/markdoc/nodes/index.ts
- src/markdoc/tags/htmlTag.markdoc.js
- src/markdoc/tags/index.ts
- yarn.lock
uses a workaround from https://github.com/markdoc/markdoc/issues/10
had to remove the next plugin to implement it, but just tweaked to ingest the .md files manually
> add html parsing to docs

- pages/deployments/architecture.md
- pages/how-to/deploy/microservice.md
- pages/how-to/deploy/pipelines.md
- pages/how-to/deploy/pr-automation.md
- pages/how-to/set-up/controllers.md
- pages/how-to/set-up/mgmt-cluster.md
- pages/how-to/set-up/rbac.md
- pages/how-to/set-up/scm-connection.md
- pages/how-to/set-up/workload-cluster.md
- src/NavData.tsx
handful of changes after running through how-to section e2e
> changes after runthrough

- pages/reference/configuring-cloud-provider.md
> docs: Update Azure CLI setup

- pages/how-to/set-up/controllers.md
- src/generated/pages.json
the {% endif %} yaml line was causing a bug where the rest of the page wouldn't render, setting process to false here tells the parser to just read the code block as plaintext
> fix controller set up page

- src/NavData.tsx
Makes it more easily discoverable.
> Move api reference to top level for fleet management

- pages/how-to/set-up/controllers.md
for some reason this isn't a happy path anymore, just disable as its unnecessary
> Explicitly disable proxy protocol for nginx for now

- generated/routes.json
- pages/plural-features/continuous-deployment/observer.md
- src/routing/docs-structure.ts
> feat(docs): document observers under continuous deployment

- .github/PULL_REQUEST_TEMPLATE.md
- pages/getting-started/advanced-config/sandboxing.md
- pages/plural-features/flows/preview-environments.md
Puts the full url in the list (people don't read the rest) and adds a bit to a callout
> Make image vendoring more clear

- generated/routes.json
- pages/plural-features/continuous-deployment/lua.md
- add doc for `utils.*` functions
- error handling
> extend lua doc

- Makefile
- generated/routes.json
- pages/getting-started/first-steps/cli-quickstart.md
- pages/getting-started/first-steps/index.md
- pages/getting-started/first-steps/plural-cloud.md
- pages/getting-started/how-to-use/cleaning-up.md
- pages/getting-started/how-to-use/controllers.md
- pages/getting-started/how-to-use/microservice.md
- pages/getting-started/how-to-use/observability.md
- pages/getting-started/how-to-use/scm-connection.md
- src/routing/docs-structure.ts
Make docs changes to highlight and further explain benefits of Plural Cloud, and guide users to it as the default.
> Docs for Plural Cloud
